[tool.poetry]
name = "kayaku"
version = "0.0.1"
description = "An powerful and flexible configuration solution."
authors = ["BlueGlassBlock <blueglassblock@outlook.com>"]
license = "MIT"
include = ["src/kayaku"]
readme = "README.md"
classifiers = [
    "Typing :: Typed",
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
]


[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.0"
creart = "^0.2.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
tomli = "^2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
